source 'https://github.com/CocoaPods/Specs.git'

# ignoring warning from pods
inhibit_all_warnings!

target "PhotoBrowserDemo" do

pod 'SDWebImage', :git => 'https://github.com/arpeggi/SDWebImage', :tag => '3.8.2.1'
pod 'SDWebImage/GIF', :git => 'https://github.com/arpeggi/SDWebImage', :tag => '3.8.2.1'
pod 'DACircularProgress'
pod 'pop'

end
